import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/reducer/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Trillo App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-[#F5F6F8]">
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
